definitions:
  auth.ForgotPasswordRequest:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  auth.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  auth.RegisterConfirmRequest:
    properties:
      token:
        type: string
    required:
    - token
    type: object
  auth.RegisterRequest:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
      repeat_password:
        type: string
      username:
        maxLength: 42
        minLength: 3
        type: string
    required:
    - email
    - password
    - repeat_password
    - username
    type: object
  auth.ResetPasswordRequest:
    properties:
      password:
        minLength: 6
        type: string
      repeat_password:
        type: string
      token:
        type: string
    required:
    - password
    - repeat_password
    - token
    type: object
  catalog.CategoryResponse:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  catalog.ColorResponse:
    properties:
      color:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  catalog.GarmentResponse:
    properties:
      category:
        $ref: '#/definitions/catalog.CategoryResponse'
      color:
        $ref: '#/definitions/catalog.ColorResponse'
      count:
        type: integer
      id:
        type: integer
      image:
        type: string
      size:
        type: string
    type: object
  core.APIError:
    properties:
      fields:
        additionalProperties:
          type: string
        type: object
      message:
        type: string
    type: object
  core.APIResponse:
    properties:
      data: {}
      error:
        $ref: '#/definitions/core.APIError'
      success:
        type: boolean
    type: object
info:
  contact: {}
paths:
  /api/v1/auth/forgot:
    post:
      consumes:
      - application/json
      parameters:
      - description: Email address
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/auth.ForgotPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Reset email sent
          schema:
            allOf:
            - $ref: '#/definitions/core.APIResponse'
            - properties:
                data:
                  additionalProperties:
                    type: string
                  type: object
              type: object
        "400":
          description: Bad request
          schema:
            allOf:
            - $ref: '#/definitions/core.APIResponse'
            - properties:
                error:
                  $ref: '#/definitions/core.APIError'
              type: object
      summary: Request password reset
      tags:
      - auth
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Login credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/auth.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully logged in
          schema:
            allOf:
            - $ref: '#/definitions/core.APIResponse'
            - properties:
                data:
                  additionalProperties:
                    type: string
                  type: object
              type: object
        "400":
          description: Bad request
          schema:
            allOf:
            - $ref: '#/definitions/core.APIResponse'
            - properties:
                error:
                  $ref: '#/definitions/core.APIError'
              type: object
        "401":
          description: Unauthorized
          schema:
            allOf:
            - $ref: '#/definitions/core.APIResponse'
            - properties:
                error:
                  $ref: '#/definitions/core.APIError'
              type: object
      summary: Login user
      tags:
      - auth
  /api/v1/auth/logout:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: Successfully logged out
          schema:
            allOf:
            - $ref: '#/definitions/core.APIResponse'
            - properties:
                data:
                  additionalProperties:
                    type: string
                  type: object
              type: object
      summary: Logout user
      tags:
      - auth
  /api/v1/auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: Register credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/auth.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully logged in
          schema:
            allOf:
            - $ref: '#/definitions/core.APIResponse'
            - properties:
                data:
                  additionalProperties:
                    type: string
                  type: object
              type: object
        "400":
          description: Bad request
          schema:
            allOf:
            - $ref: '#/definitions/core.APIResponse'
            - properties:
                error:
                  $ref: '#/definitions/core.APIError'
              type: object
      summary: Register user
      tags:
      - auth
  /api/v1/auth/register-confirm:
    post:
      consumes:
      - application/json
      parameters:
      - description: Confirmation token
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/auth.RegisterConfirmRequest'
      produces:
      - application/json
      responses:
        "201":
          description: User successfully registered
          schema:
            allOf:
            - $ref: '#/definitions/core.APIResponse'
            - properties:
                data:
                  additionalProperties:
                    type: string
                  type: object
              type: object
        "400":
          description: Bad request
          schema:
            allOf:
            - $ref: '#/definitions/core.APIResponse'
            - properties:
                error:
                  $ref: '#/definitions/core.APIError'
              type: object
      summary: Confirm user registration
      tags:
      - auth
  /api/v1/auth/reset:
    post:
      consumes:
      - application/json
      parameters:
      - description: Password reset data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/auth.ResetPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Password successfully reset
          schema:
            allOf:
            - $ref: '#/definitions/core.APIResponse'
            - properties:
                data:
                  additionalProperties:
                    type: string
                  type: object
              type: object
        "400":
          description: Bad request
          schema:
            allOf:
            - $ref: '#/definitions/core.APIResponse'
            - properties:
                error:
                  $ref: '#/definitions/core.APIError'
              type: object
      summary: Reset password
      tags:
      - auth
  /api/v1/catalog/categories:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: Successfully get categories
          schema:
            allOf:
            - $ref: '#/definitions/core.APIResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/catalog.CategoryResponse'
                  type: array
              type: object
        "400":
          description: Bad request
          schema:
            allOf:
            - $ref: '#/definitions/core.APIResponse'
            - properties:
                error:
                  $ref: '#/definitions/core.APIError'
              type: object
      summary: Ger categories
      tags:
      - catalog
  /api/v1/catalog/colors:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: Successfully get colors
          schema:
            allOf:
            - $ref: '#/definitions/core.APIResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/catalog.ColorResponse'
                  type: array
              type: object
        "400":
          description: Bad request
          schema:
            allOf:
            - $ref: '#/definitions/core.APIResponse'
            - properties:
                error:
                  $ref: '#/definitions/core.APIError'
              type: object
      summary: Ger colors
      tags:
      - catalog
  /api/v1/catalog/garments:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: Successfully get garments
          schema:
            allOf:
            - $ref: '#/definitions/core.APIResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/catalog.GarmentResponse'
                  type: array
              type: object
        "400":
          description: Bad request
          schema:
            allOf:
            - $ref: '#/definitions/core.APIResponse'
            - properties:
                error:
                  $ref: '#/definitions/core.APIError'
              type: object
      summary: Get garments
      tags:
      - catalog
swagger: "2.0"
